# Form implementation generated from reading ui file 'analysis_1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(538, 518)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 50, 371, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_import = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout.addWidget(self.btn_import)
        self.line_file_path = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.line_file_path.setText("")
        self.line_file_path.setReadOnly(True)
        self.line_file_path.setObjectName("line_file_path")
        self.horizontalLayout.addWidget(self.line_file_path)
        self.btn_analyze = QtWidgets.QPushButton(parent=Form)
        self.btn_analyze.setGeometry(QtCore.QRect(140, 150, 201, 25))
        self.btn_analyze.setObjectName("btn_analyze")
        self.textBrowser_log = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_log.setGeometry(QtCore.QRect(60, 190, 371, 301))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.textBrowser_log.setFont(font)
        self.textBrowser_log.setObjectName("textBrowser_log")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "分析"))
        self.btn_import.setText(_translate("Form", "选择文件"))
        self.line_file_path.setPlaceholderText(_translate("Form", "请选择文件"))
        self.btn_analyze.setText(_translate("Form", "开始训练模型和分析"))
